name: Lint Check

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: ESLint Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install server dependencies
      run: npm ci
      working-directory: ./server

    - name: Install client dependencies
      run: npm ci  
      working-directory: ./client

    - name: Lint server
      run: npm run lint
      working-directory: ./server

    - name: Lint client
      run: npm run lint
      working-directory: ./client

    - name: Comment PR with lint results
      if: github.event_name == 'pull_request' && failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ ESLint checks failed! Please fix the linting errors and push again.'
          })
